/****************************************************************************
** Meta object code from reading C++ file 'PrimitivePatchesInterface.h'
**
** Created by: The Qt Meta Object Compiler version 67 (Qt 5.15.16)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include <memory>
#include "src/Interface/PrimitivePatchesInterface.h"
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'PrimitivePatchesInterface.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 67
#error "This file was generated using the moc from 5.15.16. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
QT_WARNING_PUSH
QT_WARNING_DISABLE_DEPRECATED
struct qt_meta_stringdata_PrimitivePatchesInterface_t {
    QByteArrayData data[79];
    char stringdata0[1306];
};
#define QT_MOC_LITERAL(idx, ofs, len) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_PrimitivePatchesInterface_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
static const qt_meta_stringdata_PrimitivePatchesInterface_t qt_meta_stringdata_PrimitivePatchesInterface = {
    {
QT_MOC_LITERAL(0, 0, 25), // "PrimitivePatchesInterface"
QT_MOC_LITERAL(1, 26, 20), // "mouseMovedOnMapEvent"
QT_MOC_LITERAL(2, 47, 0), // ""
QT_MOC_LITERAL(3, 48, 7), // "Vector3"
QT_MOC_LITERAL(4, 56, 11), // "newPosition"
QT_MOC_LITERAL(5, 68, 13), // "TerrainModel*"
QT_MOC_LITERAL(6, 82, 5), // "model"
QT_MOC_LITERAL(7, 88, 22), // "mouseClickedOnMapEvent"
QT_MOC_LITERAL(8, 111, 13), // "mousePosInMap"
QT_MOC_LITERAL(9, 125, 10), // "mouseInMap"
QT_MOC_LITERAL(10, 136, 12), // "QMouseEvent*"
QT_MOC_LITERAL(11, 149, 5), // "event"
QT_MOC_LITERAL(12, 155, 24), // "createPatchWithOperation"
QT_MOC_LITERAL(13, 180, 3), // "pos"
QT_MOC_LITERAL(14, 184, 16), // "setSelectedShape"
QT_MOC_LITERAL(15, 201, 31), // "ImplicitPatch::PredefinedShapes"
QT_MOC_LITERAL(16, 233, 8), // "newShape"
QT_MOC_LITERAL(17, 242, 19), // "setCurrentOperation"
QT_MOC_LITERAL(18, 262, 34), // "ImplicitPatch::CompositionFun..."
QT_MOC_LITERAL(19, 297, 12), // "newOperation"
QT_MOC_LITERAL(20, 310, 21), // "setCurrentPositioning"
QT_MOC_LITERAL(21, 332, 30), // "ImplicitPatch::PositionalLabel"
QT_MOC_LITERAL(22, 363, 11), // "positioning"
QT_MOC_LITERAL(23, 375, 10), // "resetPatch"
QT_MOC_LITERAL(24, 386, 25), // "updateMapWithCurrentPatch"
QT_MOC_LITERAL(25, 412, 16), // "setSelectedWidth"
QT_MOC_LITERAL(26, 429, 6), // "newVal"
QT_MOC_LITERAL(27, 436, 17), // "setSelectedHeight"
QT_MOC_LITERAL(28, 454, 16), // "setSelectedDepth"
QT_MOC_LITERAL(29, 471, 16), // "setSelectedSigma"
QT_MOC_LITERAL(30, 488, 25), // "setSelectedBlendingFactor"
QT_MOC_LITERAL(31, 514, 23), // "addNoiseOnSelectedPatch"
QT_MOC_LITERAL(32, 538, 28), // "addDistortionOnSelectedPatch"
QT_MOC_LITERAL(33, 567, 24), // "addSpreadOnSelectedPatch"
QT_MOC_LITERAL(34, 592, 11), // "rippleScene"
QT_MOC_LITERAL(35, 604, 19), // "deformationFromFlow"
QT_MOC_LITERAL(36, 624, 17), // "savePatchesAsFile"
QT_MOC_LITERAL(37, 642, 11), // "std::string"
QT_MOC_LITERAL(38, 654, 8), // "filename"
QT_MOC_LITERAL(39, 663, 19), // "loadPatchesFromFile"
QT_MOC_LITERAL(40, 683, 13), // "hotReloadFile"
QT_MOC_LITERAL(41, 697, 17), // "autoGeneratePasse"
QT_MOC_LITERAL(42, 715, 5), // "GridF"
QT_MOC_LITERAL(43, 721, 14), // "terrainSurface"
QT_MOC_LITERAL(44, 736, 6), // "GridV3"
QT_MOC_LITERAL(45, 743, 9), // "waterFlow"
QT_MOC_LITERAL(46, 753, 14), // "surfaceNormals"
QT_MOC_LITERAL(47, 768, 20), // "std::vector<Vector3>"
QT_MOC_LITERAL(48, 789, 18), // "availablePositions"
QT_MOC_LITERAL(49, 808, 17), // "autoGenerateDelta"
QT_MOC_LITERAL(50, 826, 16), // "autoGenerateMotu"
QT_MOC_LITERAL(51, 843, 21), // "autoGenerateLongShore"
QT_MOC_LITERAL(52, 865, 23), // "structureAutoGeneration"
QT_MOC_LITERAL(53, 889, 27), // "updateSelectedPrimitiveItem"
QT_MOC_LITERAL(54, 917, 16), // "QListWidgetItem*"
QT_MOC_LITERAL(55, 934, 7), // "current"
QT_MOC_LITERAL(56, 942, 8), // "previous"
QT_MOC_LITERAL(57, 951, 31), // "openPrimitiveModificationDialog"
QT_MOC_LITERAL(58, 983, 4), // "item"
QT_MOC_LITERAL(59, 988, 24), // "modifyPrimitiveHierarchy"
QT_MOC_LITERAL(60, 1013, 10), // "ID_to_move"
QT_MOC_LITERAL(61, 1024, 9), // "relatedID"
QT_MOC_LITERAL(62, 1034, 14), // "HIERARCHY_TYPE"
QT_MOC_LITERAL(63, 1049, 8), // "relation"
QT_MOC_LITERAL(64, 1058, 11), // "QDropEvent*"
QT_MOC_LITERAL(65, 1070, 19), // "openFileForNewPatch"
QT_MOC_LITERAL(66, 1090, 15), // "setMainFilename"
QT_MOC_LITERAL(67, 1106, 15), // "newMainFilename"
QT_MOC_LITERAL(68, 1122, 15), // "findAllSubfiles"
QT_MOC_LITERAL(69, 1138, 23), // "loadTransformationRules"
QT_MOC_LITERAL(70, 1162, 18), // "addParametricPoint"
QT_MOC_LITERAL(71, 1181, 5), // "point"
QT_MOC_LITERAL(72, 1187, 22), // "displayParametricCurve"
QT_MOC_LITERAL(73, 1210, 18), // "displayPatchesTree"
QT_MOC_LITERAL(74, 1229, 28), // "moveDebugBoxWithControlPoint"
QT_MOC_LITERAL(75, 1258, 14), // "translatePatch"
QT_MOC_LITERAL(76, 1273, 11), // "translation"
QT_MOC_LITERAL(77, 1285, 11), // "rotatePatch"
QT_MOC_LITERAL(78, 1297, 8) // "rotation"

    },
    "PrimitivePatchesInterface\0"
    "mouseMovedOnMapEvent\0\0Vector3\0newPosition\0"
    "TerrainModel*\0model\0mouseClickedOnMapEvent\0"
    "mousePosInMap\0mouseInMap\0QMouseEvent*\0"
    "event\0createPatchWithOperation\0pos\0"
    "setSelectedShape\0ImplicitPatch::PredefinedShapes\0"
    "newShape\0setCurrentOperation\0"
    "ImplicitPatch::CompositionFunction\0"
    "newOperation\0setCurrentPositioning\0"
    "ImplicitPatch::PositionalLabel\0"
    "positioning\0resetPatch\0updateMapWithCurrentPatch\0"
    "setSelectedWidth\0newVal\0setSelectedHeight\0"
    "setSelectedDepth\0setSelectedSigma\0"
    "setSelectedBlendingFactor\0"
    "addNoiseOnSelectedPatch\0"
    "addDistortionOnSelectedPatch\0"
    "addSpreadOnSelectedPatch\0rippleScene\0"
    "deformationFromFlow\0savePatchesAsFile\0"
    "std::string\0filename\0loadPatchesFromFile\0"
    "hotReloadFile\0autoGeneratePasse\0GridF\0"
    "terrainSurface\0GridV3\0waterFlow\0"
    "surfaceNormals\0std::vector<Vector3>\0"
    "availablePositions\0autoGenerateDelta\0"
    "autoGenerateMotu\0autoGenerateLongShore\0"
    "structureAutoGeneration\0"
    "updateSelectedPrimitiveItem\0"
    "QListWidgetItem*\0current\0previous\0"
    "openPrimitiveModificationDialog\0item\0"
    "modifyPrimitiveHierarchy\0ID_to_move\0"
    "relatedID\0HIERARCHY_TYPE\0relation\0"
    "QDropEvent*\0openFileForNewPatch\0"
    "setMainFilename\0newMainFilename\0"
    "findAllSubfiles\0loadTransformationRules\0"
    "addParametricPoint\0point\0"
    "displayParametricCurve\0displayPatchesTree\0"
    "moveDebugBoxWithControlPoint\0"
    "translatePatch\0translation\0rotatePatch\0"
    "rotation"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_PrimitivePatchesInterface[] = {

 // content:
       8,       // revision
       0,       // classname
       0,    0, // classinfo
      40,   14, // methods
       0,    0, // properties
       0,    0, // enums/sets
       0,    0, // constructors
       0,       // flags
       0,       // signalCount

 // slots: name, argc, parameters, tag, flags
       1,    2,  214,    2, 0x0a /* Public */,
       7,    4,  219,    2, 0x0a /* Public */,
      12,    1,  228,    2, 0x0a /* Public */,
      14,    1,  231,    2, 0x0a /* Public */,
      17,    1,  234,    2, 0x0a /* Public */,
      20,    1,  237,    2, 0x0a /* Public */,
      23,    0,  240,    2, 0x0a /* Public */,
      24,    0,  241,    2, 0x0a /* Public */,
      25,    1,  242,    2, 0x0a /* Public */,
      27,    1,  245,    2, 0x0a /* Public */,
      28,    1,  248,    2, 0x0a /* Public */,
      29,    1,  251,    2, 0x0a /* Public */,
      30,    1,  254,    2, 0x0a /* Public */,
      31,    0,  257,    2, 0x0a /* Public */,
      32,    0,  258,    2, 0x0a /* Public */,
      33,    0,  259,    2, 0x0a /* Public */,
      34,    0,  260,    2, 0x0a /* Public */,
      35,    0,  261,    2, 0x0a /* Public */,
      36,    1,  262,    2, 0x0a /* Public */,
      39,    1,  265,    2, 0x0a /* Public */,
      40,    0,  268,    2, 0x0a /* Public */,
      41,    4,  269,    2, 0x0a /* Public */,
      49,    4,  278,    2, 0x0a /* Public */,
      50,    4,  287,    2, 0x0a /* Public */,
      51,    4,  296,    2, 0x0a /* Public */,
      52,    0,  305,    2, 0x0a /* Public */,
      53,    2,  306,    2, 0x0a /* Public */,
      53,    1,  311,    2, 0x2a /* Public | MethodCloned */,
      57,    1,  314,    2, 0x0a /* Public */,
      59,    4,  317,    2, 0x0a /* Public */,
      65,    0,  326,    2, 0x0a /* Public */,
      66,    1,  327,    2, 0x0a /* Public */,
      68,    0,  330,    2, 0x0a /* Public */,
      69,    0,  331,    2, 0x0a /* Public */,
      70,    1,  332,    2, 0x0a /* Public */,
      72,    0,  335,    2, 0x0a /* Public */,
      73,    0,  336,    2, 0x0a /* Public */,
      74,    0,  337,    2, 0x0a /* Public */,
      75,    1,  338,    2, 0x0a /* Public */,
      77,    1,  341,    2, 0x0a /* Public */,

 // slots: parameters
    QMetaType::Void, 0x80000000 | 3, 0x80000000 | 5,    4,    6,
    QMetaType::Void, 0x80000000 | 3, QMetaType::Bool, 0x80000000 | 10, 0x80000000 | 5,    8,    9,   11,    6,
    QMetaType::Void, 0x80000000 | 3,   13,
    QMetaType::Void, 0x80000000 | 15,   16,
    QMetaType::Void, 0x80000000 | 18,   19,
    QMetaType::Void, 0x80000000 | 21,   22,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Float,   26,
    QMetaType::Void, QMetaType::Float,   26,
    QMetaType::Void, QMetaType::Float,   26,
    QMetaType::Void, QMetaType::Float,   26,
    QMetaType::Void, QMetaType::Float,   26,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 37,   38,
    QMetaType::Void, 0x80000000 | 37,   38,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 42, 0x80000000 | 44, 0x80000000 | 44, 0x80000000 | 47,   43,   45,   46,   48,
    QMetaType::Void, 0x80000000 | 42, 0x80000000 | 44, 0x80000000 | 44, 0x80000000 | 47,   43,   45,   46,   48,
    QMetaType::Void, 0x80000000 | 42, 0x80000000 | 44, 0x80000000 | 44, 0x80000000 | 47,   43,   45,   46,   48,
    QMetaType::Void, 0x80000000 | 42, 0x80000000 | 44, 0x80000000 | 44, 0x80000000 | 47,   43,   45,   46,   48,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 54, 0x80000000 | 54,   55,   56,
    QMetaType::Void, 0x80000000 | 54,   55,
    QMetaType::Void, 0x80000000 | 54,   58,
    QMetaType::Void, QMetaType::Int, QMetaType::Int, 0x80000000 | 62, 0x80000000 | 64,   60,   61,   63,   11,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 37,   67,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 3,   71,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, 0x80000000 | 3,   76,
    QMetaType::Void, 0x80000000 | 3,   78,

       0        // eod
};

void PrimitivePatchesInterface::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
{
    if (_c == QMetaObject::InvokeMetaMethod) {
        auto *_t = static_cast<PrimitivePatchesInterface *>(_o);
        (void)_t;
        switch (_id) {
        case 0: _t->mouseMovedOnMapEvent((*reinterpret_cast< const Vector3(*)>(_a[1])),(*reinterpret_cast< TerrainModel*(*)>(_a[2]))); break;
        case 1: _t->mouseClickedOnMapEvent((*reinterpret_cast< const Vector3(*)>(_a[1])),(*reinterpret_cast< bool(*)>(_a[2])),(*reinterpret_cast< QMouseEvent*(*)>(_a[3])),(*reinterpret_cast< TerrainModel*(*)>(_a[4]))); break;
        case 2: _t->createPatchWithOperation((*reinterpret_cast< const Vector3(*)>(_a[1]))); break;
        case 3: _t->setSelectedShape((*reinterpret_cast< ImplicitPatch::PredefinedShapes(*)>(_a[1]))); break;
        case 4: _t->setCurrentOperation((*reinterpret_cast< ImplicitPatch::CompositionFunction(*)>(_a[1]))); break;
        case 5: _t->setCurrentPositioning((*reinterpret_cast< ImplicitPatch::PositionalLabel(*)>(_a[1]))); break;
        case 6: _t->resetPatch(); break;
        case 7: _t->updateMapWithCurrentPatch(); break;
        case 8: _t->setSelectedWidth((*reinterpret_cast< float(*)>(_a[1]))); break;
        case 9: _t->setSelectedHeight((*reinterpret_cast< float(*)>(_a[1]))); break;
        case 10: _t->setSelectedDepth((*reinterpret_cast< float(*)>(_a[1]))); break;
        case 11: _t->setSelectedSigma((*reinterpret_cast< float(*)>(_a[1]))); break;
        case 12: _t->setSelectedBlendingFactor((*reinterpret_cast< float(*)>(_a[1]))); break;
        case 13: _t->addNoiseOnSelectedPatch(); break;
        case 14: _t->addDistortionOnSelectedPatch(); break;
        case 15: _t->addSpreadOnSelectedPatch(); break;
        case 16: _t->rippleScene(); break;
        case 17: _t->deformationFromFlow(); break;
        case 18: _t->savePatchesAsFile((*reinterpret_cast< std::string(*)>(_a[1]))); break;
        case 19: _t->loadPatchesFromFile((*reinterpret_cast< std::string(*)>(_a[1]))); break;
        case 20: _t->hotReloadFile(); break;
        case 21: _t->autoGeneratePasse((*reinterpret_cast< const GridF(*)>(_a[1])),(*reinterpret_cast< const GridV3(*)>(_a[2])),(*reinterpret_cast< const GridV3(*)>(_a[3])),(*reinterpret_cast< const std::vector<Vector3>(*)>(_a[4]))); break;
        case 22: _t->autoGenerateDelta((*reinterpret_cast< const GridF(*)>(_a[1])),(*reinterpret_cast< const GridV3(*)>(_a[2])),(*reinterpret_cast< const GridV3(*)>(_a[3])),(*reinterpret_cast< const std::vector<Vector3>(*)>(_a[4]))); break;
        case 23: _t->autoGenerateMotu((*reinterpret_cast< const GridF(*)>(_a[1])),(*reinterpret_cast< const GridV3(*)>(_a[2])),(*reinterpret_cast< const GridV3(*)>(_a[3])),(*reinterpret_cast< const std::vector<Vector3>(*)>(_a[4]))); break;
        case 24: _t->autoGenerateLongShore((*reinterpret_cast< const GridF(*)>(_a[1])),(*reinterpret_cast< const GridV3(*)>(_a[2])),(*reinterpret_cast< const GridV3(*)>(_a[3])),(*reinterpret_cast< const std::vector<Vector3>(*)>(_a[4]))); break;
        case 25: _t->structureAutoGeneration(); break;
        case 26: _t->updateSelectedPrimitiveItem((*reinterpret_cast< QListWidgetItem*(*)>(_a[1])),(*reinterpret_cast< QListWidgetItem*(*)>(_a[2]))); break;
        case 27: _t->updateSelectedPrimitiveItem((*reinterpret_cast< QListWidgetItem*(*)>(_a[1]))); break;
        case 28: _t->openPrimitiveModificationDialog((*reinterpret_cast< QListWidgetItem*(*)>(_a[1]))); break;
        case 29: _t->modifyPrimitiveHierarchy((*reinterpret_cast< int(*)>(_a[1])),(*reinterpret_cast< int(*)>(_a[2])),(*reinterpret_cast< HIERARCHY_TYPE(*)>(_a[3])),(*reinterpret_cast< QDropEvent*(*)>(_a[4]))); break;
        case 30: _t->openFileForNewPatch(); break;
        case 31: _t->setMainFilename((*reinterpret_cast< std::string(*)>(_a[1]))); break;
        case 32: _t->findAllSubfiles(); break;
        case 33: _t->loadTransformationRules(); break;
        case 34: _t->addParametricPoint((*reinterpret_cast< const Vector3(*)>(_a[1]))); break;
        case 35: _t->displayParametricCurve(); break;
        case 36: _t->displayPatchesTree(); break;
        case 37: _t->moveDebugBoxWithControlPoint(); break;
        case 38: _t->translatePatch((*reinterpret_cast< const Vector3(*)>(_a[1]))); break;
        case 39: _t->rotatePatch((*reinterpret_cast< const Vector3(*)>(_a[1]))); break;
        default: ;
        }
    }
}

QT_INIT_METAOBJECT const QMetaObject PrimitivePatchesInterface::staticMetaObject = { {
    QMetaObject::SuperData::link<ActionInterface::staticMetaObject>(),
    qt_meta_stringdata_PrimitivePatchesInterface.data,
    qt_meta_data_PrimitivePatchesInterface,
    qt_static_metacall,
    nullptr,
    nullptr
} };


const QMetaObject *PrimitivePatchesInterface::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
}

void *PrimitivePatchesInterface::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, qt_meta_stringdata_PrimitivePatchesInterface.stringdata0))
        return static_cast<void*>(this);
    return ActionInterface::qt_metacast(_clname);
}

int PrimitivePatchesInterface::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
{
    _id = ActionInterface::qt_metacall(_c, _id, _a);
    if (_id < 0)
        return _id;
    if (_c == QMetaObject::InvokeMetaMethod) {
        if (_id < 40)
            qt_static_metacall(this, _c, _id, _a);
        _id -= 40;
    } else if (_c == QMetaObject::RegisterMethodArgumentMetaType) {
        if (_id < 40)
            *reinterpret_cast<int*>(_a[0]) = -1;
        _id -= 40;
    }
    return _id;
}
struct qt_meta_stringdata_PatchReplacementDialog_t {
    QByteArrayData data[5];
    char stringdata0[44];
};
#define QT_MOC_LITERAL(idx, ofs, len) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_PatchReplacementDialog_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
static const qt_meta_stringdata_PatchReplacementDialog_t qt_meta_stringdata_PatchReplacementDialog = {
    {
QT_MOC_LITERAL(0, 0, 22), // "PatchReplacementDialog"
QT_MOC_LITERAL(1, 23, 4), // "open"
QT_MOC_LITERAL(2, 28, 0), // ""
QT_MOC_LITERAL(3, 29, 6), // "cancel"
QT_MOC_LITERAL(4, 36, 7) // "confirm"

    },
    "PatchReplacementDialog\0open\0\0cancel\0"
    "confirm"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_PatchReplacementDialog[] = {

 // content:
       8,       // revision
       0,       // classname
       0,    0, // classinfo
       3,   14, // methods
       0,    0, // properties
       0,    0, // enums/sets
       0,    0, // constructors
       0,       // flags
       0,       // signalCount

 // slots: name, argc, parameters, tag, flags
       1,    0,   29,    2, 0x0a /* Public */,
       3,    0,   30,    2, 0x0a /* Public */,
       4,    0,   31,    2, 0x0a /* Public */,

 // slots: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,

       0        // eod
};

void PatchReplacementDialog::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
{
    if (_c == QMetaObject::InvokeMetaMethod) {
        auto *_t = static_cast<PatchReplacementDialog *>(_o);
        (void)_t;
        switch (_id) {
        case 0: _t->open(); break;
        case 1: _t->cancel(); break;
        case 2: _t->confirm(); break;
        default: ;
        }
    }
    (void)_a;
}

QT_INIT_METAOBJECT const QMetaObject PatchReplacementDialog::staticMetaObject = { {
    QMetaObject::SuperData::link<QDialog::staticMetaObject>(),
    qt_meta_stringdata_PatchReplacementDialog.data,
    qt_meta_data_PatchReplacementDialog,
    qt_static_metacall,
    nullptr,
    nullptr
} };


const QMetaObject *PatchReplacementDialog::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
}

void *PatchReplacementDialog::qt_metacast(const char *_clname)
{
    if (!_clname) return nullptr;
    if (!strcmp(_clname, qt_meta_stringdata_PatchReplacementDialog.stringdata0))
        return static_cast<void*>(this);
    return QDialog::qt_metacast(_clname);
}

int PatchReplacementDialog::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
{
    _id = QDialog::qt_metacall(_c, _id, _a);
    if (_id < 0)
        return _id;
    if (_c == QMetaObject::InvokeMetaMethod) {
        if (_id < 3)
            qt_static_metacall(this, _c, _id, _a);
        _id -= 3;
    } else if (_c == QMetaObject::RegisterMethodArgumentMetaType) {
        if (_id < 3)
            *reinterpret_cast<int*>(_a[0]) = -1;
        _id -= 3;
    }
    return _id;
}
QT_WARNING_POP
QT_END_MOC_NAMESPACE
